package com.dongqh.luckyhub.membership;
import com.dongqh.luckyhub.membership.dto.*; import com.dongqh.luckyhub.membership.enums.MembershipCardType; import com.dongqh.luckyhub.membership.service.MembershipService; import com.dongqh.luckyhub.rbac.entity.SysUser; import com.dongqh.luckyhub.rbac.mapper.SysUserMapper; import org.junit.jupiter.api.*; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.boot.test.context.SpringBootTest; import org.springframework.jdbc.core.JdbcTemplate; import java.time.*; import java.util.UUID; import static org.assertj.core.api.Assertions.*;
@SpringBootTest class MembershipServiceTests {
 @Autowired MembershipService service;@Autowired JdbcTemplate jdbc;@Autowired SysUserMapper users;Long userId;
 @BeforeEach void setup(){jdbc.update("DELETE FROM membership_grant_record");jdbc.update("DELETE FROM user_membership");jdbc.update("DELETE FROM membership_product");SysUser u=new SysUser();u.setUsername("member-"+UUID.randomUUID());u.setPassword("x");u.setNickname("会员用户");u.setStatus(1);users.insert(u);userId=u.getId();}
 @AfterEach void clean(){jdbc.update("DELETE FROM membership_grant_record");jdbc.update("DELETE FROM user_membership");jdbc.update("DELETE FROM membership_product");users.deleteById(userId);}
 @Test void renewsFromExistingExpiryAndRepeatsBusinessIdWithoutExtension(){var p=service.createProduct(new CreateMembershipProductCommand("YEAR","年卡","MEMBER",MembershipCardType.YEAR,365,9900L,9000,2,12000));var first=service.purchase(new PurchaseMembershipCommand("BUY-Y1",p.id(),userId));var repeated=service.purchase(new PurchaseMembershipCommand("BUY-Y1",p.id(),userId));assertThat(repeated.expiresAt()).isEqualTo(first.expiresAt());var second=service.purchase(new PurchaseMembershipCommand("BUY-Y2",p.id(),userId));assertThat(Duration.between(first.expiresAt(),second.expiresAt()).toDays()).isEqualTo(365);assertThat(service.activeBenefit(userId)).isPresent().get().extracting(v->v.discountBasisPoints()).isEqualTo(9000);}
 @Test void rejectsBusinessReuseWithDifferentIdentity(){var p=service.createProduct(new CreateMembershipProductCommand("MONTH","月卡","MEMBER",MembershipCardType.MONTH,30,1000L,9500,1,10000));service.purchase(new PurchaseMembershipCommand("SAME",p.id(),userId));assertThatThrownBy(()->service.purchase(new PurchaseMembershipCommand("SAME",p.id()+1,userId))).hasMessageContaining("幂等");}
}
