package com.dongqh.luckyhub.order.service.impl;
import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;import com.baomidou.mybatisplus.extension.plugins.pagination.Page;import com.dongqh.luckyhub.catalog.enums.ProductType;import com.dongqh.luckyhub.catalog.model.PurchasableSkuSnapshot;import com.dongqh.luckyhub.catalog.service.CatalogService;import com.dongqh.luckyhub.common.exception.BusinessException;import com.dongqh.luckyhub.common.result.PageResponse;import com.dongqh.luckyhub.coupon.model.CouponLockSnapshot;import com.dongqh.luckyhub.coupon.service.CouponService;import com.dongqh.luckyhub.inventory.channel.dto.ReserveChannelStockCommand;import com.dongqh.luckyhub.inventory.channel.service.ChannelInventoryService;import com.dongqh.luckyhub.membership.model.ActiveMembershipBenefit;import com.dongqh.luckyhub.membership.service.MembershipService;import com.dongqh.luckyhub.order.dto.*;import com.dongqh.luckyhub.order.entity.MallOrder;import com.dongqh.luckyhub.order.enums.*;import com.dongqh.luckyhub.order.mapper.MallOrderMapper;import com.dongqh.luckyhub.order.model.OrderPriceQuote;import com.dongqh.luckyhub.order.service.*;import com.dongqh.luckyhub.order.vo.CashOrderView;import com.dongqh.luckyhub.shipping.entity.ShippingAddressSnapshot;import com.dongqh.luckyhub.shipping.entity.ShippingOrder;import com.dongqh.luckyhub.shipping.enums.ShippingErrorCode;import com.dongqh.luckyhub.shipping.enums.ShippingSourceType;import com.dongqh.luckyhub.shipping.mapper.ShippingOrderMapper;import com.dongqh.luckyhub.shipping.service.ShippingAddressSnapshotService;import com.dongqh.luckyhub.shipping.vo.ShippingAddressSnapshotView;import org.springframework.dao.DuplicateKeyException;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.*;import java.time.LocalDateTime;import java.time.temporal.ChronoUnit;import java.util.*;
@Service public class CashOrderServiceImpl implements CashOrderService {
 private final MallOrderMapper mapper;private final CatalogService catalog;private final MembershipService memberships;private final CouponService coupons;private final ChannelInventoryService inventory;private final OrderPricingService pricing;private final ShippingAddressSnapshotService snapshots;private final ShippingOrderMapper shippingOrders;
 public CashOrderServiceImpl(MallOrderMapper m,CatalogService c,MembershipService ms,CouponService cs,ChannelInventoryService i,OrderPricingService p,ShippingAddressSnapshotService s,ShippingOrderMapper so){mapper=m;catalog=c;memberships=ms;coupons=cs;inventory=i;pricing=p;snapshots=s;shippingOrders=so;}
 @Transactional(isolation=Isolation.READ_COMMITTED) public CashOrderView create(long userId,CreateCashOrderCommand c){String no=c.orderNo().trim();MallOrder old=find(no);if(old!=null)return existing(old,userId,c);PurchasableSkuSnapshot sku=catalog.findPurchasableSku(c.skuId()).orElseThrow(()->error(OrderErrorCode.SKU_UNAVAILABLE));validateAddressShape(sku.productType(),c.addressId());ActiveMembershipBenefit member=memberships.activeBenefit(userId).orElse(null);OrderPriceQuote preliminary=pricing.quote(sku,c.quantity(),member,null);CouponLockSnapshot coupon=c.userCouponId()==null?null:coupons.lockForOrder(userId,c.userCouponId(),no,sku.productId(),preliminary.amountAfterMembershipCent(),member!=null);OrderPriceQuote quote=pricing.quote(sku,c.quantity(),member,coupon);MallOrder o=build(no,userId,c,sku,quote);try{mapper.insert(o);}catch(DuplicateKeyException e){return existing(find(no),userId,c);}if(c.addressId()!=null){ShippingAddressSnapshot snapshot=snapshots.create(userId,c.addressId(),ShippingSourceType.CASH_ORDER,String.valueOf(o.getId()));if(mapper.attachAddressSnapshot(o.getId(),snapshot.getId())!=1)throw shippingError(ShippingErrorCode.SHIPPING_IDEMPOTENCY_CONFLICT);o.setAddressSnapshotId(snapshot.getId());}inventory.reserve(new ReserveChannelStockCommand(sku.skuId(),"MALL",c.quantity(),no));return view(o);}
 public CashOrderView get(long userId,String no){MallOrder o=find(no.trim());if(o==null)throw error(OrderErrorCode.ORDER_NOT_FOUND);if(!o.getUserId().equals(userId))throw error(OrderErrorCode.ACCESS_DENIED);return view(o);}
 public PageResponse<CashOrderView> page(long userId,CashOrderQuery q){Page<MallOrder> p=mapper.selectPage(new Page<>(q.getPage(),q.getSize()),new LambdaQueryWrapper<MallOrder>().eq(MallOrder::getUserId,userId).eq(q.getStatus()!=null,MallOrder::getStatus,q.getStatus()).orderByDesc(MallOrder::getCreatedAt).orderByDesc(MallOrder::getId));return new PageResponse<>(p.getRecords().stream().map(this::view).toList(),p.getTotal(),p.getCurrent(),p.getSize(),p.getPages());}
 @Transactional public CashOrderView cancel(long userId,String no,String reason){MallOrder o=mapper.lockByOrderNo(no.trim());if(o==null)throw error(OrderErrorCode.ORDER_NOT_FOUND);if(!o.getUserId().equals(userId))throw error(OrderErrorCode.ACCESS_DENIED);return cancelLocked(o,reason);}
 @Transactional public int cancelExpired(int limit){int n=0;for(MallOrder o:mapper.findExpired(LocalDateTime.now(),limit)){MallOrder locked=mapper.lockByOrderNo(o.getOrderNo());if(locked!=null&&locked.getStatus()==CashOrderStatus.PENDING_PAYMENT){cancelLocked(locked,"支付超时");n++;}}return n;}
 private CashOrderView cancelLocked(MallOrder o,String reason){if(o.getStatus()==CashOrderStatus.CANCELLED)return view(o);if(o.getStatus()!=CashOrderStatus.PENDING_PAYMENT)throw error(OrderErrorCode.STATE_CONFLICT);if(mapper.cancel(o.getOrderNo(),reason)!=1)throw error(OrderErrorCode.STATE_CONFLICT);inventory.release(o.getOrderNo());if(o.getUserCouponId()!=null)coupons.releaseForOrder(o.getUserCouponId(),o.getOrderNo());return view(find(o.getOrderNo()));}
 private MallOrder build(String no,long user,CreateCashOrderCommand c,PurchasableSkuSnapshot s,OrderPriceQuote q){MallOrder o=new MallOrder();o.setOrderNo(no);o.setUserId(user);o.setSkuId(s.skuId());o.setQuantity(c.quantity());o.setProductCode(s.productCode());o.setProductName(s.productName());o.setSkuCode(s.skuCode());o.setSkuName(s.skuName());o.setProductType(s.productType());o.setImageUrl(s.imageUrl());o.setUnitPriceCent(s.cashPriceCent());o.setOriginalAmountCent(q.originalAmountCent());o.setMembershipLevel(q.membershipLevel());o.setMembershipDiscountBasisPoints(q.membershipDiscountBasisPoints());o.setMembershipDiscountCent(q.membershipDiscountCent());o.setAmountAfterMembershipCent(q.amountAfterMembershipCent());o.setUserCouponId(q.userCouponId());o.setCouponTemplateId(q.couponTemplateId());o.setCouponName(q.couponName());o.setCouponDiscountCent(q.couponDiscountCent());o.setPayableAmountCent(q.payableAmountCent());o.setStatus(CashOrderStatus.PENDING_PAYMENT);o.setPaymentDeadline(LocalDateTime.now().plusMinutes(30).truncatedTo(ChronoUnit.MILLIS));return o;}
 private CashOrderView existing(MallOrder o,long user,CreateCashOrderCommand c){if(o==null||!o.getUserId().equals(user)||!o.getSkuId().equals(c.skuId())||!o.getQuantity().equals(c.quantity())||!Objects.equals(o.getUserCouponId(),c.userCouponId())||!sameAddress(o,c.addressId()))throw error(OrderErrorCode.IDEMPOTENCY_CONFLICT);return view(o);}
 private MallOrder find(String no){return mapper.selectOne(new LambdaQueryWrapper<MallOrder>().eq(MallOrder::getOrderNo,no));}
 private CashOrderView view(MallOrder o){ShippingOrder so=o.getShippingOrderId()==null?null:shippingOrders.selectById(o.getShippingOrderId());return new CashOrderView(o.getId(),o.getOrderNo(),o.getUserId(),o.getSkuId(),o.getQuantity(),o.getProductCode(),o.getProductName(),o.getSkuCode(),o.getSkuName(),o.getProductType(),o.getImageUrl(),o.getUnitPriceCent(),o.getOriginalAmountCent(),o.getMembershipLevel(),o.getMembershipDiscountBasisPoints(),o.getMembershipDiscountCent(),o.getAmountAfterMembershipCent(),o.getUserCouponId(),o.getCouponTemplateId(),o.getCouponName(),o.getCouponDiscountCent(),o.getPayableAmountCent(),o.getStatus(),o.getPaymentDeadline(),o.getPaidAt(),o.getCancelledAt(),o.getCancelReason(),o.getCreatedAt(),o.getUpdatedAt(),snapshotView(o.getAddressSnapshotId()),o.getShippingOrderId(),so==null?null:so.getShippingNo(),so==null?null:so.getStatus());}
 private void validateAddressShape(ProductType type,Long addressId){if((type==ProductType.PHYSICAL)!=(addressId!=null))throw shippingError(ShippingErrorCode.SHIPPING_REQUEST_INVALID);}
 private boolean sameAddress(MallOrder o,Long addressId){if(o.getAddressSnapshotId()==null)return addressId==null;return addressId!=null&&Objects.equals(snapshots.require(o.getAddressSnapshotId()).getAddressId(),addressId);}
 private ShippingAddressSnapshotView snapshotView(Long id){if(id==null)return null;ShippingAddressSnapshot s=snapshots.require(id);return new ShippingAddressSnapshotView(s.getId(),s.getSnapshotNo(),s.getReceiverMasked(),s.getPhoneMasked(),s.getRegionMasked());}
 private BusinessException error(OrderErrorCode e){return new BusinessException(e);}
 private BusinessException shippingError(ShippingErrorCode e){return new BusinessException(e);}
}
