package com.dongqh.luckyhub.fulfillment;
import com.dongqh.luckyhub.fulfillment.dto.CreateFulfillmentTaskCommand;import com.dongqh.luckyhub.fulfillment.enums.*;import com.dongqh.luckyhub.fulfillment.model.*;import com.dongqh.luckyhub.fulfillment.service.FulfillmentTaskService;import com.dongqh.luckyhub.fulfillment.worker.FulfillmentWorker;import com.dongqh.luckyhub.integration.simulator.*;
import org.junit.jupiter.api.*;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.jdbc.core.JdbcTemplate;import static org.assertj.core.api.Assertions.assertThat;
@SpringBootTest class FulfillmentEndToEndTests {
 @Autowired FulfillmentTaskService tasks;@Autowired FulfillmentWorker worker;@Autowired SimulatorFailureRuleService rules;@Autowired JdbcTemplate jdbc;
 @AfterEach void clean(){jdbc.update("DELETE FROM fulfillment_attempt");jdbc.update("DELETE FROM fulfillment_quarantine");jdbc.update("DELETE FROM fulfillment_task");jdbc.update("DELETE FROM sim_coupon_record");jdbc.update("DELETE FROM sim_points_record");jdbc.update("DELETE FROM sim_membership_record");jdbc.update("DELETE FROM sim_logistics_record");jdbc.update("DELETE FROM sim_failure_rule");}
 @Test void lostSuccessIsQueriedAndNeverExecutedTwiceEvenAtExecutionLimit(){rules.configure(FulfillmentType.MEMBERSHIP,SimulatorFailureMode.UNKNOWN_AFTER_SUCCESS,1);tasks.create(new CreateFulfillmentTaskCommand("LOST-E2E","TEST","1",FulfillmentType.MEMBERSHIP,1L,new MembershipFulfillmentPayload("VIP",30),1));worker.runBatch();assertThat(tasks.get("LOST-E2E").status()).isEqualTo(FulfillmentStatus.RECONCILING);worker.runBatch();assertThat(tasks.get("LOST-E2E").status()).isEqualTo(FulfillmentStatus.SUCCEEDED);assertThat(tasks.get("LOST-E2E").attemptCount()).isOne();assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM sim_membership_record WHERE fulfillment_no='LOST-E2E'",Integer.class)).isOne();assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM fulfillment_attempt WHERE fulfillment_no='LOST-E2E' AND operation='EXECUTE'",Integer.class)).isOne();assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM fulfillment_attempt WHERE fulfillment_no='LOST-E2E' AND operation='QUERY'",Integer.class)).isOne();}
 @Test void unknownBeforeQueriesNotFoundThenExecutesSuccessfully(){rules.configure(FulfillmentType.POINTS,SimulatorFailureMode.UNKNOWN_BEFORE,1);tasks.create(new CreateFulfillmentTaskCommand("UNKNOWN-E2E","TEST","1",FulfillmentType.POINTS,1L,new PointsFulfillmentPayload(8,"奖励"),5));worker.runBatch();worker.runBatch();assertThat(tasks.get("UNKNOWN-E2E").status()).isEqualTo(FulfillmentStatus.PENDING);worker.runBatch();assertThat(tasks.get("UNKNOWN-E2E").status()).isEqualTo(FulfillmentStatus.SUCCEEDED);assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM sim_points_record WHERE fulfillment_no='UNKNOWN-E2E'",Integer.class)).isOne();}
}
