package com.dongqh.luckyhub.fulfillment;
import com.dongqh.luckyhub.auth.model.JwtPayload;import com.dongqh.luckyhub.auth.security.*;import com.dongqh.luckyhub.common.result.PageResponse;import com.dongqh.luckyhub.fulfillment.enums.*;import com.dongqh.luckyhub.fulfillment.model.PointsFulfillmentPayload;import com.dongqh.luckyhub.fulfillment.service.FulfillmentTaskService;import com.dongqh.luckyhub.fulfillment.vo.FulfillmentTaskView;import com.dongqh.luckyhub.integration.simulator.SimulatorFailureRuleService;import com.dongqh.luckyhub.rbac.constant.PermissionCodes;import com.dongqh.luckyhub.rbac.service.UserPermissionService;
import org.junit.jupiter.api.*;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc;import org.springframework.http.MediaType;import org.springframework.test.context.bean.override.mockito.MockitoBean;import org.springframework.test.web.servlet.MockMvc;import java.util.*;import static org.mockito.ArgumentMatchers.*;import static org.mockito.Mockito.*;import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
@SpringBootTest @AutoConfigureMockMvc class FulfillmentControllerTests {
 @Autowired MockMvc mvc;@MockitoBean FulfillmentTaskService service;@MockitoBean SimulatorFailureRuleService rules;@MockitoBean JwtService jwt;@MockitoBean SessionService sessions;@MockitoBean UserPermissionService permissions;
 @BeforeEach void auth(){when(jwt.parse("token")).thenReturn(new JwtPayload(77L,"admin","s1"));when(sessions.isValid("s1",77L)).thenReturn(true);when(permissions.findPermissionCodes(77L)).thenReturn(Set.of(PermissionCodes.FULFILLMENT_CREATE,PermissionCodes.FULFILLMENT_READ,PermissionCodes.FULFILLMENT_OPERATE,PermissionCodes.SIMULATOR_CONTROL));when(service.create(any())).thenReturn(view(FulfillmentStatus.PENDING));when(service.get(anyString())).thenReturn(view(FulfillmentStatus.PENDING));when(service.page(any())).thenReturn(new PageResponse<>(List.of(view(FulfillmentStatus.PENDING)),1,1,20,1));when(service.retryQuarantined(anyString(),anyLong(),any())).thenReturn(view(FulfillmentStatus.PENDING));when(service.terminate(anyString(),anyLong(),any())).thenReturn(view(FulfillmentStatus.TERMINATED));}
 @Test void exposesCreateReadPageRetryTerminateAndFailureRule() throws Exception {mvc.perform(post("/api/admin/fulfillment/tasks").header("Authorization","Bearer token").contentType(MediaType.APPLICATION_JSON).content(body())).andExpect(status().isCreated()).andExpect(jsonPath("$.data.fulfillmentNo").value("API-1"));mvc.perform(get("/api/admin/fulfillment/tasks/API-1").header("Authorization","Bearer token")).andExpect(status().isOk());mvc.perform(get("/api/admin/fulfillment/tasks").header("Authorization","Bearer token")).andExpect(status().isOk()).andExpect(jsonPath("$.data.total").value(1));mvc.perform(post("/api/admin/fulfillment/tasks/API-1/retry").header("Authorization","Bearer token").contentType(MediaType.APPLICATION_JSON).content("{\"note\":\"人工确认\"}")).andExpect(status().isOk());mvc.perform(post("/api/admin/fulfillment/tasks/API-1/terminate").header("Authorization","Bearer token").contentType(MediaType.APPLICATION_JSON).content("{\"note\":\"停止\"}")).andExpect(status().isOk());mvc.perform(post("/api/admin/simulators/failure-rules").header("Authorization","Bearer token").contentType(MediaType.APPLICATION_JSON).content("{\"fulfillmentType\":\"POINTS\",\"failureMode\":\"RETRYABLE\",\"count\":1}")).andExpect(status().isOk());verify(rules).configure(any(),any(),eq(1));}
 @Test void invalidCreateUsesBadRequestEnvelope() throws Exception {mvc.perform(post("/api/admin/fulfillment/tasks").header("Authorization","Bearer token").contentType(MediaType.APPLICATION_JSON).content(body().replace("API-1",""))).andExpect(status().isBadRequest()).andExpect(jsonPath("$.code").value(30000));}
 private String body(){return "{\"fulfillmentNo\":\"API-1\",\"sourceType\":\"MANUAL\",\"sourceId\":\"M-1\",\"fulfillmentType\":\"POINTS\",\"targetUserId\":11,\"payload\":{\"points\":100,\"reason\":\"补发\"},\"maxAttempts\":5}";}
 private FulfillmentTaskView view(FulfillmentStatus s){return new FulfillmentTaskView(1L,"API-1","MANUAL","M-1",FulfillmentType.POINTS,11L,new PointsFulfillmentPayload(100,"补发"),"f",s,0,5,null,null,null,null,null,s==FulfillmentStatus.TERMINATED?java.time.LocalDateTime.now():null,null,null);}
}
