package com.dongqh.luckyhub.fulfillment;
import com.dongqh.luckyhub.fulfillment.dto.CreateFulfillmentTaskCommand;import com.dongqh.luckyhub.fulfillment.enums.*;import com.dongqh.luckyhub.fulfillment.model.*;import com.dongqh.luckyhub.fulfillment.service.*;import com.dongqh.luckyhub.fulfillment.worker.FulfillmentWorker;import com.dongqh.luckyhub.integration.simulator.*;
import org.junit.jupiter.api.*;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.jdbc.core.JdbcTemplate;import java.sql.Timestamp;import java.time.*;import static org.assertj.core.api.Assertions.assertThat;
@SpringBootTest class FulfillmentRecoveryTests {
 @Autowired FulfillmentTaskService tasks;@Autowired FulfillmentStateService state;@Autowired FulfillmentWorker worker;@Autowired SimulatorFailureRuleService rules;@Autowired JdbcTemplate jdbc;
 @AfterEach void clean(){jdbc.update("DELETE FROM fulfillment_attempt");jdbc.update("DELETE FROM fulfillment_quarantine");jdbc.update("DELETE FROM fulfillment_task");jdbc.update("DELETE FROM sim_points_record");jdbc.update("DELETE FROM sim_coupon_record");jdbc.update("DELETE FROM sim_failure_rule");}
 @Test void retryUsesConfiguredDelayAndMaxAttemptQuarantines(){rules.configure(FulfillmentType.POINTS,SimulatorFailureMode.RETRYABLE,2);tasks.create(command("RETRY-1",2));LocalDateTime before=LocalDateTime.now();worker.runBatch();var retry=tasks.get("RETRY-1");assertThat(retry.status()).isEqualTo(FulfillmentStatus.RETRY_WAITING);assertThat(retry.nextAttemptAt()).isAfterOrEqualTo(before.plusNanos(900_000_000));jdbc.update("UPDATE fulfillment_task SET next_attempt_at=NOW(3) WHERE fulfillment_no='RETRY-1'");worker.runBatch();assertThat(tasks.get("RETRY-1").status()).isEqualTo(FulfillmentStatus.QUARANTINED);assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM fulfillment_quarantine WHERE fulfillment_no='RETRY-1'",Integer.class)).isOne();}
 @Test void permanentFailureImmediatelyQuarantines(){rules.configure(FulfillmentType.COUPON,SimulatorFailureMode.PERMANENT,1);tasks.create(new CreateFulfillmentTaskCommand("PERM-1","TEST","1",FulfillmentType.COUPON,1L,new CouponFulfillmentPayload("C",1),5));worker.runBatch();assertThat(tasks.get("PERM-1").status()).isEqualTo(FulfillmentStatus.QUARANTINED);}
 @Test void expiredProcessingLeaseBecomesReconciliation(){tasks.create(command("EXPIRED-1",5));state.claimDue(1,Duration.ofSeconds(30));jdbc.update("UPDATE fulfillment_task SET lease_until=? WHERE fulfillment_no='EXPIRED-1'",Timestamp.valueOf(LocalDateTime.now().minusSeconds(1)));assertThat(state.recoverExpiredLeases(10)).isOne();assertThat(tasks.get("EXPIRED-1").status()).isEqualTo(FulfillmentStatus.RECONCILING);}
 private CreateFulfillmentTaskCommand command(String no,int max){return new CreateFulfillmentTaskCommand(no,"TEST","1",FulfillmentType.POINTS,1L,new PointsFulfillmentPayload(10,"奖励"),max);}
}
