package com.dongqh.luckyhub.fulfillment;
import com.dongqh.luckyhub.common.exception.BusinessException;import com.dongqh.luckyhub.fulfillment.dto.CreateFulfillmentTaskCommand;import com.dongqh.luckyhub.fulfillment.enums.*;import com.dongqh.luckyhub.fulfillment.model.PointsFulfillmentPayload;import com.dongqh.luckyhub.fulfillment.model.FulfillmentClaim;import com.dongqh.luckyhub.fulfillment.service.*;import com.dongqh.luckyhub.integration.gateway.GatewayResult;
import org.junit.jupiter.api.*;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.jdbc.core.JdbcTemplate;
import java.time.Duration;import java.util.*;import java.util.concurrent.*;import java.util.stream.IntStream;import static org.assertj.core.api.Assertions.*;
@SpringBootTest class FulfillmentLeaseConcurrencyTests {
 @Autowired FulfillmentTaskService tasks;@Autowired FulfillmentStateService state;@Autowired JdbcTemplate jdbc;
 @AfterEach void clean(){jdbc.update("DELETE FROM fulfillment_attempt");jdbc.update("DELETE FROM fulfillment_quarantine");jdbc.update("DELETE FROM fulfillment_task");}
 @Test void onlyOneOfTwentyClaimersWins() throws Exception {tasks.create(new CreateFulfillmentTaskCommand("LEASE-1","TEST","1",FulfillmentType.POINTS,1L,new PointsFulfillmentPayload(1,"x"),5));ExecutorService pool=Executors.newFixedThreadPool(20);try{CountDownLatch start=new CountDownLatch(1);List<Future<List<FulfillmentClaim>>> fs=IntStream.range(0,20).mapToObj(i->pool.submit(()->{start.await();return state.claimDue(1,Duration.ofSeconds(30));})).toList();start.countDown();int claims=0;for(Future<List<FulfillmentClaim>> f:fs)claims+=f.get(15,TimeUnit.SECONDS).size();assertThat(claims).isOne();}finally{pool.shutdownNow();}}
 @Test void staleLeaseTokenCannotComplete(){tasks.create(new CreateFulfillmentTaskCommand("LEASE-2","TEST","2",FulfillmentType.POINTS,1L,new PointsFulfillmentPayload(1,"x"),5));FulfillmentClaim claim=state.claimDue(1,Duration.ofSeconds(30)).get(0);FulfillmentClaim stale=new FulfillmentClaim(claim.taskId(),claim.fulfillmentNo(),claim.fulfillmentType(),claim.targetUserId(),claim.requestPayload(),claim.operation(),"wrong-token",claim.claimedAt(),claim.leaseUntil());assertThatThrownBy(()->state.recordResult(stale,GatewayResult.succeeded("EXT"),1)).isInstanceOfSatisfying(BusinessException.class,e->assertThat(e.getErrorCode()).isEqualTo(FulfillmentErrorCode.LEASE_CONFLICT));assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM fulfillment_attempt WHERE fulfillment_no='LEASE-2'",Integer.class)).isZero();}
}
