package com.dongqh.luckyhub.fulfillment;
import com.dongqh.luckyhub.fulfillment.dto.CreateFulfillmentTaskCommand;import com.dongqh.luckyhub.fulfillment.enums.*;import com.dongqh.luckyhub.fulfillment.model.CouponFulfillmentPayload;import com.dongqh.luckyhub.fulfillment.service.*;import com.dongqh.luckyhub.fulfillment.worker.FulfillmentWorker;import com.dongqh.luckyhub.integration.gateway.*;
import org.junit.jupiter.api.*;import org.springframework.beans.factory.annotation.*;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.boot.test.context.TestConfiguration;import org.springframework.context.annotation.*;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.transaction.support.TransactionSynchronizationManager;
import java.util.concurrent.atomic.AtomicBoolean;import static org.assertj.core.api.Assertions.assertThat;
@SpringBootTest class FulfillmentWorkerTests {
 @Autowired FulfillmentTaskService tasks;@Autowired FulfillmentWorker worker;@Autowired JdbcTemplate jdbc;@Autowired AtomicBoolean transactionObserved;
 @AfterEach void clean(){jdbc.update("DELETE FROM fulfillment_attempt");jdbc.update("DELETE FROM fulfillment_quarantine");jdbc.update("DELETE FROM fulfillment_task");jdbc.update("DELETE FROM sim_coupon_record");}
 @Test void callsGatewayOutsideTransactionAndRecordsOneSuccessfulAttempt(){tasks.create(new CreateFulfillmentTaskCommand("WORK-1","TEST","1",FulfillmentType.COUPON,1L,new CouponFulfillmentPayload("C20",1),5));assertThat(worker.runBatch()).isOne();assertThat(transactionObserved).isFalse();assertThat(tasks.get("WORK-1").status()).isEqualTo(FulfillmentStatus.SUCCEEDED);assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM fulfillment_attempt WHERE fulfillment_no='WORK-1'",Integer.class)).isOne();}
 @TestConfiguration static class GatewayConfig {@Bean AtomicBoolean transactionObserved(){return new AtomicBoolean();}@Bean @Primary CouponGateway testCouponGateway(AtomicBoolean observed){return new CouponGateway(){public GatewayResult execute(CouponGrantRequest r){observed.set(TransactionSynchronizationManager.isActualTransactionActive());return GatewayResult.succeeded("TEST-EXT");}public GatewayResult query(String no){observed.set(TransactionSynchronizationManager.isActualTransactionActive());return GatewayResult.notFound();}};}}
}
