package com.dongqh.luckyhub.fulfillment.worker;
import com.dongqh.luckyhub.fulfillment.enums.AttemptOperation;import com.dongqh.luckyhub.fulfillment.model.*;import com.dongqh.luckyhub.fulfillment.service.FulfillmentStateService;import com.dongqh.luckyhub.integration.gateway.*;import org.springframework.stereotype.Component;import tools.jackson.core.JacksonException;import tools.jackson.databind.ObjectMapper;
import java.time.Duration;
@Component public class FulfillmentWorker {
 private final FulfillmentStateService state;private final CouponGateway coupons;private final PointsGateway points;private final MembershipGateway memberships;private final LogisticsGateway logistics;private final ObjectMapper json;
 public FulfillmentWorker(FulfillmentStateService state,CouponGateway coupons,PointsGateway points,MembershipGateway memberships,LogisticsGateway logistics,ObjectMapper json){this.state=state;this.coupons=coupons;this.points=points;this.memberships=memberships;this.logistics=logistics;this.json=json;}
 public int runBatch(){var claims=state.claimDue(50,Duration.ofSeconds(30));for(FulfillmentClaim claim:claims){long start=System.nanoTime();GatewayResult result;try{result=route(claim);}catch(RuntimeException e){result=GatewayResult.retryable("GATEWAY_EXCEPTION","Gateway调用异常");}long duration=Math.max(0,(System.nanoTime()-start)/1_000_000);state.recordResult(claim,result,duration);}return claims.size();}
 private GatewayResult route(FulfillmentClaim c){if(c.operation()==AttemptOperation.QUERY)return switch(c.fulfillmentType()){case COUPON->coupons.query(c.fulfillmentNo());case POINTS->points.query(c.fulfillmentNo());case MEMBERSHIP->memberships.query(c.fulfillmentNo());case LOGISTICS->logistics.query(c.fulfillmentNo());};try{return switch(c.fulfillmentType()){case COUPON->{CouponFulfillmentPayload p=json.readValue(c.requestPayload(),CouponFulfillmentPayload.class);yield coupons.execute(new CouponGrantRequest(c.fulfillmentNo(),c.targetUserId(),p.couponTemplateCode(),p.quantity()));}case POINTS->{PointsFulfillmentPayload p=json.readValue(c.requestPayload(),PointsFulfillmentPayload.class);yield points.execute(new PointsGrantRequest(c.fulfillmentNo(),c.targetUserId(),p.points(),p.reason()));}case MEMBERSHIP->{MembershipFulfillmentPayload p=json.readValue(c.requestPayload(),MembershipFulfillmentPayload.class);yield memberships.execute(new MembershipGrantRequest(c.fulfillmentNo(),c.targetUserId(),p.membershipCode(),p.durationDays()));}case LOGISTICS->{LogisticsFulfillmentPayload p=json.readValue(c.requestPayload(),LogisticsFulfillmentPayload.class);yield logistics.execute(new LogisticsCreateRequest(c.fulfillmentNo(),c.targetUserId(),p.skuCode(),p.quantity(),p.receiverMasked(),p.phoneMasked(),p.regionMasked()));}};}catch(JacksonException e){return GatewayResult.permanent("INVALID_SNAPSHOT","履约快照无法解析");}}
}
