package com.dongqh.luckyhub.membership.service.impl;
import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper; import com.dongqh.luckyhub.common.exception.BusinessException; import com.dongqh.luckyhub.membership.dto.*; import com.dongqh.luckyhub.membership.entity.*; import com.dongqh.luckyhub.membership.enums.*; import com.dongqh.luckyhub.membership.mapper.*; import com.dongqh.luckyhub.membership.model.ActiveMembershipBenefit; import com.dongqh.luckyhub.membership.service.MembershipService; import com.dongqh.luckyhub.membership.vo.*; import org.springframework.dao.DuplicateKeyException; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.*; import java.time.LocalDateTime; import java.time.temporal.ChronoUnit; import java.util.Optional;
@Service public class MembershipServiceImpl implements MembershipService {
 private final MembershipProductMapper products;private final UserMembershipMapper memberships;private final MembershipGrantRecordMapper grants;public MembershipServiceImpl(MembershipProductMapper p,UserMembershipMapper m,MembershipGrantRecordMapper g){products=p;memberships=m;grants=g;}
 @Transactional public MembershipProductView createProduct(CreateMembershipProductCommand c){validate(c);MembershipProduct p=new MembershipProduct();p.setProductCode(c.productCode().trim());p.setProductName(c.productName().trim());p.setMembershipLevel(c.membershipLevel().trim());p.setCardType(c.cardType());p.setDurationDays(c.durationDays());p.setPriceCent(c.priceCent());p.setDiscountBasisPoints(c.discountBasisPoints());p.setDailyDrawBonus(c.dailyDrawBonus());p.setPointsMultiplierBasisPoints(c.pointsMultiplierBasisPoints());p.setStatus(1);try{products.insert(p);}catch(DuplicateKeyException e){throw error(MembershipErrorCode.PRODUCT_DUPLICATE);}return view(p);}
 @Transactional(isolation=Isolation.READ_COMMITTED) public UserMembershipView purchase(PurchaseMembershipCommand c){String b=c.businessNo().trim();MembershipGrantRecord old=findGrant(b);if(old!=null)return existing(old,c);if(memberships.lockEnabledUser(c.userId())==null)throw error(MembershipErrorCode.USER_UNAVAILABLE);old=findGrant(b);if(old!=null)return existing(old,c);MembershipProduct p=products.selectById(c.membershipProductId());if(p==null||p.getStatus()!=1)throw error(MembershipErrorCode.PRODUCT_NOT_FOUND);LocalDateTime now=LocalDateTime.now().truncatedTo(ChronoUnit.MILLIS);UserMembership m=memberships.lockByUserId(c.userId());LocalDateTime start=now;LocalDateTime base=now;if(m!=null&&m.getMembershipLevel().equals(p.getMembershipLevel())&&m.getExpiresAt().isAfter(now)){start=m.getStartsAt();base=m.getExpiresAt();}LocalDateTime expiry=base.plusDays(p.getDurationDays());if(m==null){m=new UserMembership();m.setUserId(c.userId());m.setStartsAt(start);m.setVersion(0);}m.setMembershipLevel(p.getMembershipLevel());m.setExpiresAt(expiry);m.setDiscountBasisPoints(p.getDiscountBasisPoints());m.setDailyDrawBonus(p.getDailyDrawBonus());m.setPointsMultiplierBasisPoints(p.getPointsMultiplierBasisPoints());if(m.getId()==null)memberships.insert(m);else{m.setVersion(m.getVersion()+1);memberships.updateById(m);}MembershipGrantRecord g=new MembershipGrantRecord();g.setBusinessNo(b);g.setUserId(c.userId());g.setMembershipProductId(p.getId());g.setStartsAt(base);g.setExpiresAt(expiry);grants.insert(g);return view(m);}
 public Optional<UserMembershipView> getMine(long userId){return Optional.ofNullable(memberships.selectOne(new LambdaQueryWrapper<UserMembership>().eq(UserMembership::getUserId,userId))).map(this::view);}
 public Optional<ActiveMembershipBenefit> activeBenefit(long userId){LocalDateTime now=LocalDateTime.now();UserMembership m=memberships.selectOne(new LambdaQueryWrapper<UserMembership>().eq(UserMembership::getUserId,userId).gt(UserMembership::getExpiresAt,now));return Optional.ofNullable(m).map(v->new ActiveMembershipBenefit(v.getMembershipLevel(),v.getDiscountBasisPoints(),v.getDailyDrawBonus(),v.getPointsMultiplierBasisPoints(),v.getExpiresAt()));}
 private MembershipGrantRecord findGrant(String b){return grants.selectOne(new LambdaQueryWrapper<MembershipGrantRecord>().eq(MembershipGrantRecord::getBusinessNo,b));}
 private UserMembershipView existing(MembershipGrantRecord g,PurchaseMembershipCommand c){if(!g.getUserId().equals(c.userId())||!g.getMembershipProductId().equals(c.membershipProductId()))throw error(MembershipErrorCode.IDEMPOTENCY_CONFLICT);UserMembership m=memberships.selectOne(new LambdaQueryWrapper<UserMembership>().eq(UserMembership::getUserId,c.userId()));return new UserMembershipView(m.getId(),m.getUserId(),m.getMembershipLevel(),m.getStartsAt(),g.getExpiresAt(),m.getDiscountBasisPoints(),m.getDailyDrawBonus(),m.getPointsMultiplierBasisPoints());}
 private void validate(CreateMembershipProductCommand c){int expected=switch(c.cardType()){case MONTH->30;case QUARTER->90;case YEAR->365;};if(c.durationDays()!=expected)throw error(MembershipErrorCode.PRODUCT_INVALID);}
 private MembershipProductView view(MembershipProduct p){return new MembershipProductView(p.getId(),p.getProductCode(),p.getProductName(),p.getMembershipLevel(),p.getCardType(),p.getDurationDays(),p.getPriceCent(),p.getDiscountBasisPoints(),p.getDailyDrawBonus(),p.getPointsMultiplierBasisPoints(),p.getStatus());}
 private UserMembershipView view(UserMembership m){return new UserMembershipView(m.getId(),m.getUserId(),m.getMembershipLevel(),m.getStartsAt(),m.getExpiresAt(),m.getDiscountBasisPoints(),m.getDailyDrawBonus(),m.getPointsMultiplierBasisPoints());}
 private BusinessException error(MembershipErrorCode e){return new BusinessException(e);}
}
