package com.dongqh.luckyhub.fulfillment.controller;
import com.dongqh.luckyhub.auth.context.LoginContext;import com.dongqh.luckyhub.common.result.*;import com.dongqh.luckyhub.fulfillment.dto.*;import com.dongqh.luckyhub.fulfillment.service.FulfillmentTaskService;import com.dongqh.luckyhub.fulfillment.vo.FulfillmentTaskView;import com.dongqh.luckyhub.rbac.annotation.RequirePermission;import com.dongqh.luckyhub.rbac.constant.PermissionCodes;import jakarta.validation.Valid;import org.springframework.http.HttpStatus;import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/admin/fulfillment/tasks") public class FulfillmentAdminController {private final FulfillmentTaskService service;public FulfillmentAdminController(FulfillmentTaskService service){this.service=service;}
 @PostMapping @ResponseStatus(HttpStatus.CREATED) @RequirePermission(PermissionCodes.FULFILLMENT_CREATE) public ApiResponse<FulfillmentTaskView> create(@Valid @RequestBody CreateFulfillmentTaskRequest request){return ApiResponse.success(service.create(request.toCommand()));}
 @GetMapping @RequirePermission(PermissionCodes.FULFILLMENT_READ) public ApiResponse<PageResponse<FulfillmentTaskView>> page(@Valid @ModelAttribute FulfillmentTaskQuery query){return ApiResponse.success(service.page(query));}
 @GetMapping("/{fulfillmentNo}") @RequirePermission(PermissionCodes.FULFILLMENT_READ) public ApiResponse<FulfillmentTaskView> get(@PathVariable String fulfillmentNo){return ApiResponse.success(service.get(fulfillmentNo));}
 @PostMapping("/{fulfillmentNo}/retry") @RequirePermission(PermissionCodes.FULFILLMENT_OPERATE) public ApiResponse<FulfillmentTaskView> retry(@PathVariable String fulfillmentNo,@Valid @RequestBody(required=false) FulfillmentOperationCommand command){return ApiResponse.success(service.retryQuarantined(fulfillmentNo,LoginContext.require().userId(),command==null?null:command.note()));}
 @PostMapping("/{fulfillmentNo}/terminate") @RequirePermission(PermissionCodes.FULFILLMENT_OPERATE) public ApiResponse<FulfillmentTaskView> terminate(@PathVariable String fulfillmentNo,@Valid @RequestBody(required=false) FulfillmentOperationCommand command){return ApiResponse.success(service.terminate(fulfillmentNo,LoginContext.require().userId(),command==null?null:command.note()));}
}
