package com.dongqh.luckyhub.coupon.service.impl;
import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper; import com.baomidou.mybatisplus.extension.plugins.pagination.Page; import com.dongqh.luckyhub.common.exception.BusinessException; import com.dongqh.luckyhub.common.result.PageResponse; import com.dongqh.luckyhub.coupon.dto.*; import com.dongqh.luckyhub.coupon.entity.*; import com.dongqh.luckyhub.coupon.enums.*; import com.dongqh.luckyhub.coupon.mapper.*; import com.dongqh.luckyhub.coupon.model.CouponLockSnapshot; import com.dongqh.luckyhub.coupon.service.CouponService; import com.dongqh.luckyhub.coupon.vo.*; import com.dongqh.luckyhub.rbac.entity.SysUser; import com.dongqh.luckyhub.rbac.mapper.SysUserMapper; import org.springframework.dao.DuplicateKeyException; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.*; import java.time.LocalDateTime;
@Service public class CouponServiceImpl implements CouponService {
 private final CouponTemplateMapper templates;private final UserCouponMapper coupons;private final CouponIssueRecordMapper issues;private final SysUserMapper users;
 public CouponServiceImpl(CouponTemplateMapper t,UserCouponMapper c,CouponIssueRecordMapper i,SysUserMapper u){templates=t;coupons=c;issues=i;users=u;}
 @Transactional public CouponTemplateView createTemplate(CreateCouponTemplateCommand c){validate(c);CouponTemplate t=new CouponTemplate();t.setTemplateCode(c.templateCode().trim());t.setTemplateName(c.templateName().trim());t.setCouponType(c.couponType());t.setThresholdCent(c.thresholdCent());t.setDiscountCent(c.discountCent());t.setApplicableProductId(c.applicableProductId());t.setValidFrom(c.validFrom());t.setValidUntil(c.validUntil());t.setPerUserLimit(c.perUserLimit());t.setStackableWithMembership(c.stackableWithMembership());t.setStatus(1);try{templates.insert(t);}catch(DuplicateKeyException e){throw error(CouponErrorCode.TEMPLATE_DUPLICATE);}return view(t);}
 @Transactional(isolation=Isolation.READ_COMMITTED) public UserCouponView issue(IssueCouponCommand c){String b=c.businessNo().trim();CouponIssueRecord old=issues.selectOne(new LambdaQueryWrapper<CouponIssueRecord>().eq(CouponIssueRecord::getBusinessNo,b));if(old!=null)return existingIssue(old,c);CouponTemplate t=templates.lockById(c.templateId());if(t==null||t.getStatus()!=1)throw error(CouponErrorCode.TEMPLATE_NOT_FOUND);SysUser u=users.selectById(c.userId());if(u==null||u.getStatus()!=1)throw error(CouponErrorCode.COUPON_UNAVAILABLE);long count=issues.selectCount(new LambdaQueryWrapper<CouponIssueRecord>().eq(CouponIssueRecord::getUserId,c.userId()).eq(CouponIssueRecord::getTemplateId,c.templateId()));if(count>=t.getPerUserLimit())throw error(CouponErrorCode.ISSUE_LIMIT);UserCoupon uc=new UserCoupon();uc.setCouponNo(c.couponNo().trim());uc.setTemplateId(t.getId());uc.setUserId(c.userId());uc.setStatus(UserCouponStatus.AVAILABLE);uc.setValidFrom(t.getValidFrom());uc.setValidUntil(t.getValidUntil());uc.setVersion(0);CouponIssueRecord record=new CouponIssueRecord();record.setBusinessNo(b);record.setTemplateId(t.getId());record.setUserId(c.userId());try{coupons.insert(uc);record.setUserCouponId(uc.getId());issues.insert(record);}catch(DuplicateKeyException e){throw error(CouponErrorCode.COUPON_IDEMPOTENCY_CONFLICT);}return view(uc);}
 public UserCouponView getMine(long userId,long id){UserCoupon c=coupons.selectById(id);if(c==null||!c.getUserId().equals(userId))throw error(CouponErrorCode.COUPON_NOT_FOUND);return view(c);}
 public PageResponse<UserCouponView> pageMine(long userId,long page,long size){Page<UserCoupon> p=coupons.selectPage(new Page<>(page,size),new LambdaQueryWrapper<UserCoupon>().eq(UserCoupon::getUserId,userId).orderByDesc(UserCoupon::getCreatedAt).orderByDesc(UserCoupon::getId));return new PageResponse<>(p.getRecords().stream().map(this::view).toList(),p.getTotal(),p.getCurrent(),p.getSize(),p.getPages());}
 @Transactional public CouponLockSnapshot lockForOrder(long userId,long id,String orderNo,Long productId,long amount,boolean member){UserCoupon c=coupons.selectById(id);if(c==null||!c.getUserId().equals(userId))throw error(CouponErrorCode.COUPON_NOT_FOUND);CouponTemplate t=templates.selectById(c.getTemplateId());if(c.getStatus()==UserCouponStatus.LOCKED&&orderNo.equals(c.getLockedOrderNo()))return snapshot(c,t,amount,productId,member);if(c.getStatus()!=UserCouponStatus.AVAILABLE)throw error(CouponErrorCode.COUPON_UNAVAILABLE);validateApplicable(t,amount,productId,member);if(coupons.lock(id,userId,orderNo)!=1)throw error(CouponErrorCode.COUPON_STATE_CONFLICT);return snapshot(c,t,amount,productId,member);}
 @Transactional public void useForOrder(long id,String orderNo){UserCoupon c=coupons.selectById(id);if(c!=null&&c.getStatus()==UserCouponStatus.USED&&orderNo.equals(c.getUsedOrderNo()))return;if(coupons.use(id,orderNo)!=1)throw error(CouponErrorCode.COUPON_STATE_CONFLICT);}
 @Transactional public void releaseForOrder(long id,String orderNo){UserCoupon c=coupons.selectById(id);if(c!=null&&c.getStatus()==UserCouponStatus.AVAILABLE)return;if(coupons.release(id,orderNo)!=1)throw error(CouponErrorCode.COUPON_STATE_CONFLICT);}
 @Transactional public int expireAvailable(){return coupons.expireAvailable();}
 private UserCouponView existingIssue(CouponIssueRecord old,IssueCouponCommand c){if(!old.getTemplateId().equals(c.templateId())||!old.getUserId().equals(c.userId()))throw error(CouponErrorCode.COUPON_IDEMPOTENCY_CONFLICT);UserCoupon uc=coupons.selectById(old.getUserCouponId());if(!uc.getCouponNo().equals(c.couponNo().trim()))throw error(CouponErrorCode.COUPON_IDEMPOTENCY_CONFLICT);return view(uc);}
 private CouponLockSnapshot snapshot(UserCoupon c,CouponTemplate t,long amount,Long productId,boolean member){validateApplicable(t,amount,productId,member);return new CouponLockSnapshot(c.getId(),t.getId(),t.getTemplateName(),Math.min(t.getDiscountCent(),amount));}
 private void validateApplicable(CouponTemplate t,long amount,Long productId,boolean member){LocalDateTime now=LocalDateTime.now();if(t==null||t.getStatus()!=1||now.isBefore(t.getValidFrom())||!now.isBefore(t.getValidUntil())||amount<t.getThresholdCent()||(t.getApplicableProductId()!=null&&!t.getApplicableProductId().equals(productId))||(member&&!t.getStackableWithMembership()))throw error(CouponErrorCode.COUPON_NOT_APPLICABLE);}
 private void validate(CreateCouponTemplateCommand c){if(!c.validUntil().isAfter(c.validFrom())||(c.couponType()==CouponType.NO_THRESHOLD&&c.thresholdCent()!=0)||(c.couponType()==CouponType.THRESHOLD&&c.thresholdCent()<=0))throw error(CouponErrorCode.COUPON_NOT_APPLICABLE);}
 private CouponTemplateView view(CouponTemplate t){return new CouponTemplateView(t.getId(),t.getTemplateCode(),t.getTemplateName(),t.getCouponType(),t.getThresholdCent(),t.getDiscountCent(),t.getApplicableProductId(),t.getValidFrom(),t.getValidUntil(),t.getPerUserLimit(),t.getStackableWithMembership(),t.getStatus());}
 private UserCouponView view(UserCoupon c){return new UserCouponView(c.getId(),c.getCouponNo(),c.getTemplateId(),c.getUserId(),c.getStatus(),c.getValidFrom(),c.getValidUntil(),c.getLockedOrderNo(),c.getUsedOrderNo());}
 private BusinessException error(CouponErrorCode e){return new BusinessException(e);}
}
