package com.dongqh.luckyhub.fulfillment.service.impl;
import com.dongqh.luckyhub.common.exception.BusinessException;import com.dongqh.luckyhub.fulfillment.config.FulfillmentProperties;import com.dongqh.luckyhub.fulfillment.enums.*;import com.dongqh.luckyhub.fulfillment.model.FulfillmentClaim;import com.dongqh.luckyhub.fulfillment.service.FulfillmentStateService;import com.dongqh.luckyhub.integration.gateway.GatewayResult;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
import java.sql.Timestamp;import java.time.*;import java.util.*;
@Service public class FulfillmentStateServiceImpl implements FulfillmentStateService {
 private final JdbcTemplate jdbc;private final FulfillmentProperties properties;public FulfillmentStateServiceImpl(JdbcTemplate jdbc,FulfillmentProperties properties){this.jdbc=jdbc;this.properties=properties;}
 @Transactional public List<FulfillmentClaim> claimDue(int limit,Duration leaseDuration){if(limit<1||limit>1000||leaseDuration==null||leaseDuration.isZero()||leaseDuration.isNegative())throw new IllegalArgumentException("领取参数不合法");LocalDateTime now=LocalDateTime.now(),until=now.plus(leaseDuration);List<Row> rows=jdbc.query("""
  SELECT id,fulfillment_no,fulfillment_type,target_user_id,request_payload,status FROM fulfillment_task
  WHERE status IN ('PENDING','RETRY_WAITING','RECONCILING') AND (next_attempt_at IS NULL OR next_attempt_at<=?)
  ORDER BY id LIMIT ? FOR UPDATE SKIP LOCKED
  """,(rs,n)->new Row(rs.getLong(1),rs.getString(2),FulfillmentType.valueOf(rs.getString(3)),rs.getLong(4),rs.getString(5),FulfillmentStatus.valueOf(rs.getString(6))),Timestamp.valueOf(now),limit);List<FulfillmentClaim> claims=new ArrayList<>();for(Row row:rows){String token=UUID.randomUUID().toString();int changed=jdbc.update("UPDATE fulfillment_task SET status='PROCESSING',lease_token=?,lease_until=? WHERE id=? AND status=?",token,Timestamp.valueOf(until),row.id,row.status.name());if(changed==1)claims.add(new FulfillmentClaim(row.id,row.no,row.type,row.user,row.payload,row.status==FulfillmentStatus.RECONCILING?AttemptOperation.QUERY:AttemptOperation.EXECUTE,token,now,until));}return List.copyOf(claims);}
 @Transactional public void recordResult(FulfillmentClaim claim,GatewayResult result,long durationMs){if(claim==null||result==null||durationMs<0)throw new IllegalArgumentException("结果参数不合法");TaskRow task=jdbc.query("SELECT status,lease_token,attempt_count,max_attempts FROM fulfillment_task WHERE id=? FOR UPDATE",rs->rs.next()?new TaskRow(FulfillmentStatus.valueOf(rs.getString(1)),rs.getString(2),rs.getInt(3),rs.getInt(4)):null,claim.taskId());if(task==null||task.status!=FulfillmentStatus.PROCESSING||!Objects.equals(task.token,claim.leaseToken()))throw new BusinessException(FulfillmentErrorCode.LEASE_CONFLICT);Integer sequence=jdbc.queryForObject("SELECT COALESCE(MAX(sequence_no),0)+1 FROM fulfillment_attempt WHERE task_id=?",Integer.class,claim.taskId());int executionAttempts=task.attempts+(claim.operation()==AttemptOperation.EXECUTE?1:0);FailureCategory category=category(result.outcome());LocalDateTime finished=LocalDateTime.now();jdbc.update("INSERT INTO fulfillment_attempt(task_id,fulfillment_no,sequence_no,operation,outcome,started_at,finished_at,duration_ms,external_reference,error_category,error_code,error_message) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)",claim.taskId(),claim.fulfillmentNo(),sequence,claim.operation().name(),result.outcome().name(),Timestamp.valueOf(claim.claimedAt()),Timestamp.valueOf(finished),durationMs,result.externalReference(),category==null?null:category.name(),result.errorCode(),result.safeMessage());Transition transition=transition(result,claim.operation(),executionAttempts,task.maxAttempts,finished);jdbc.update("UPDATE fulfillment_task SET status=?,attempt_count=?,next_attempt_at=?,lease_token=NULL,lease_until=NULL,external_reference=COALESCE(?,external_reference),last_error_category=?,last_error_code=?,last_error_message=?,completed_at=? WHERE id=?",transition.status.name(),executionAttempts,transition.next==null?null:Timestamp.valueOf(transition.next),result.externalReference(),category==null?null:category.name(),result.errorCode(),result.safeMessage(),transition.completed==null?null:Timestamp.valueOf(transition.completed),claim.taskId());if(transition.status==FulfillmentStatus.QUARANTINED)jdbc.update("INSERT INTO fulfillment_quarantine(task_id,fulfillment_no,reason,error_category,error_code,error_message,quarantined_at) VALUES(?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE reason=VALUES(reason),error_category=VALUES(error_category),error_code=VALUES(error_code),error_message=VALUES(error_message),quarantined_at=VALUES(quarantined_at),resolved_at=NULL,resolution=NULL,resolved_by=NULL,resolution_note=NULL",claim.taskId(),claim.fulfillmentNo(),"履约失败",category==null?null:category.name(),result.errorCode(),result.safeMessage(),Timestamp.valueOf(finished));}
 @Transactional public int recoverExpiredLeases(int limit){if(limit<1||limit>1000)throw new IllegalArgumentException("limit必须为1到1000");return jdbc.update("UPDATE fulfillment_task SET status='RECONCILING',next_attempt_at=NOW(3),lease_token=NULL,lease_until=NULL,last_error_category='UNKNOWN',last_error_code='LEASE_EXPIRED',last_error_message='履约租约过期，转入安全对账' WHERE status='PROCESSING' AND lease_until<NOW(3) ORDER BY id LIMIT ?",limit);}
 private Transition transition(GatewayResult r,AttemptOperation op,int attempts,int max,LocalDateTime now){return switch(r.outcome()){case SUCCEEDED->new Transition(FulfillmentStatus.SUCCEEDED,null,now);case UNKNOWN->new Transition(FulfillmentStatus.RECONCILING,now,null);case RETRYABLE_FAILURE->attempts>=max?new Transition(FulfillmentStatus.QUARANTINED,null,null):new Transition(FulfillmentStatus.RETRY_WAITING,now.plus(backoff(attempts)),null);case PERMANENT_FAILURE->new Transition(FulfillmentStatus.QUARANTINED,null,null);case NOT_FOUND->op==AttemptOperation.QUERY?new Transition(FulfillmentStatus.PENDING,now,null):new Transition(FulfillmentStatus.RETRY_WAITING,now.plus(backoff(attempts)),null);};}
 private Duration backoff(int attempts){long multiplier=1L<<Math.min(30,Math.max(0,attempts-1));Duration calculated;try{calculated=properties.baseDelay().multipliedBy(multiplier);}catch(ArithmeticException e){calculated=properties.maxDelay();}return calculated.compareTo(properties.maxDelay())>0?properties.maxDelay():calculated;}
 private FailureCategory category(GatewayOutcome o){return switch(o){case RETRYABLE_FAILURE->FailureCategory.RETRYABLE;case PERMANENT_FAILURE->FailureCategory.PERMANENT;case UNKNOWN->FailureCategory.UNKNOWN;default->null;};}
 private record Row(long id,String no,FulfillmentType type,long user,String payload,FulfillmentStatus status){}private record TaskRow(FulfillmentStatus status,String token,int attempts,int maxAttempts){}private record Transition(FulfillmentStatus status,LocalDateTime next,LocalDateTime completed){}
}
