package com.dongqh.luckyhub.fulfillment.service.impl;
import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper; import com.baomidou.mybatisplus.extension.plugins.pagination.Page; import com.dongqh.luckyhub.common.exception.BusinessException; import com.dongqh.luckyhub.common.result.PageResponse; import com.dongqh.luckyhub.fulfillment.dto.*; import com.dongqh.luckyhub.fulfillment.entity.FulfillmentTask; import com.dongqh.luckyhub.fulfillment.enums.*; import com.dongqh.luckyhub.fulfillment.mapper.FulfillmentTaskMapper; import com.dongqh.luckyhub.fulfillment.model.*; import com.dongqh.luckyhub.fulfillment.service.FulfillmentTaskService; import com.dongqh.luckyhub.fulfillment.vo.FulfillmentTaskView; import org.springframework.dao.DuplicateKeyException; import org.springframework.stereotype.Service; import tools.jackson.core.JacksonException; import tools.jackson.databind.ObjectMapper;
import java.nio.charset.StandardCharsets;import java.security.*;import java.time.LocalDateTime;import java.util.HexFormat;
@Service public class FulfillmentTaskServiceImpl implements FulfillmentTaskService {
 private final FulfillmentTaskMapper mapper;private final ObjectMapper json;public FulfillmentTaskServiceImpl(FulfillmentTaskMapper mapper,ObjectMapper json){this.mapper=mapper;this.json=json;}
 public FulfillmentTaskView create(CreateFulfillmentTaskCommand c){String payload=write(c.payload());String fingerprint=digest(c.sourceType()+"\n"+c.sourceId()+"\n"+c.fulfillmentType()+"\n"+c.targetUserId()+"\n"+c.maxAttempts()+"\n"+payload);FulfillmentTask old=find(c.fulfillmentNo());if(old!=null)return existing(old,fingerprint);FulfillmentTask t=new FulfillmentTask();t.setFulfillmentNo(c.fulfillmentNo());t.setSourceType(c.sourceType());t.setSourceId(c.sourceId());t.setFulfillmentType(c.fulfillmentType());t.setTargetUserId(c.targetUserId());t.setRequestPayload(payload);t.setRequestFingerprint(fingerprint);t.setStatus(FulfillmentStatus.PENDING);t.setAttemptCount(0);t.setMaxAttempts(c.maxAttempts());t.setNextAttemptAt(LocalDateTime.now());t.setVersion(0);try{mapper.insert(t);}catch(DuplicateKeyException race){return existing(find(c.fulfillmentNo()),fingerprint);}return view(t);}
 public FulfillmentTaskView get(String no){FulfillmentTask task=find(required(no));if(task==null)throw error(FulfillmentErrorCode.TASK_NOT_FOUND);return view(task);}
 public PageResponse<FulfillmentTaskView> page(FulfillmentTaskQuery q){Page<FulfillmentTask> p=mapper.selectPage(new Page<>(q.getPage(),q.getSize()),new LambdaQueryWrapper<FulfillmentTask>().eq(q.getFulfillmentType()!=null,FulfillmentTask::getFulfillmentType,q.getFulfillmentType()).eq(q.getStatus()!=null,FulfillmentTask::getStatus,q.getStatus()).eq(q.getTargetUserId()!=null,FulfillmentTask::getTargetUserId,q.getTargetUserId()).eq(q.getSourceType()!=null&&!q.getSourceType().isBlank(),FulfillmentTask::getSourceType,q.getSourceType()).eq(q.getSourceId()!=null&&!q.getSourceId().isBlank(),FulfillmentTask::getSourceId,q.getSourceId()).orderByDesc(FulfillmentTask::getCreatedAt).orderByDesc(FulfillmentTask::getId));return new PageResponse<>(p.getRecords().stream().map(this::view).toList(),p.getTotal(),p.getCurrent(),p.getSize(),p.getPages());}
 private FulfillmentTaskView existing(FulfillmentTask task,String fingerprint){if(task==null||!task.getRequestFingerprint().equals(fingerprint))throw error(FulfillmentErrorCode.IDEMPOTENCY_CONFLICT);return view(task);}
 private FulfillmentTask find(String no){return mapper.selectOne(new LambdaQueryWrapper<FulfillmentTask>().eq(FulfillmentTask::getFulfillmentNo,no));}
 private FulfillmentTaskView view(FulfillmentTask t){return new FulfillmentTaskView(t.getId(),t.getFulfillmentNo(),t.getSourceType(),t.getSourceId(),t.getFulfillmentType(),t.getTargetUserId(),read(t.getFulfillmentType(),t.getRequestPayload()),t.getRequestFingerprint(),t.getStatus(),t.getAttemptCount(),t.getMaxAttempts(),t.getNextAttemptAt(),t.getExternalReference(),t.getLastErrorCategory(),t.getLastErrorCode(),t.getLastErrorMessage(),t.getCompletedAt(),t.getCreatedAt(),t.getUpdatedAt());}
 private String write(FulfillmentPayload p){try{return json.writeValueAsString(p);}catch(JacksonException e){throw error(FulfillmentErrorCode.INVALID_PAYLOAD);}}
 private FulfillmentPayload read(FulfillmentType type,String value){try{return switch(type){case COUPON->json.readValue(value,CouponFulfillmentPayload.class);case POINTS->json.readValue(value,PointsFulfillmentPayload.class);case MEMBERSHIP->json.readValue(value,MembershipFulfillmentPayload.class);case LOGISTICS->json.readValue(value,LogisticsFulfillmentPayload.class);};}catch(JacksonException e){throw error(FulfillmentErrorCode.INVALID_PAYLOAD);}}
 private String digest(String value){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(value.getBytes(StandardCharsets.UTF_8)));}catch(NoSuchAlgorithmException e){throw new IllegalStateException(e);}}
 private String required(String v){if(v==null||v.isBlank())throw error(FulfillmentErrorCode.INVALID_PAYLOAD);return v.trim();}private BusinessException error(FulfillmentErrorCode c){return new BusinessException(c);}
}
